CREATE OR REPLACE TABLE `Users` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Firstname` VARCHAR(255) NOT NULL,
	`Lastname` VARCHAR(255) NOT NULL,
	`Email` VARCHAR(255) NOT NULL,
	`Password` VARCHAR(255) NOT NULL,
	`Admin` BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY(`id`)
);

CREATE INDEX `Users_index_0`
ON `Users` (`id`);

CREATE OR REPLACE TABLE `Tasks` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(255) NOT NULL,
	`Creation` DATETIME NOT NULL,
	`Due` DATETIME,
	`Recurrency` SMALLINT,
	`Done` BOOLEAN NOT NULL DEFAULT FALSE,
	`Notes` TEXT,
	`Project` INTEGER NOT NULL,
	PRIMARY KEY(`id`, `Project`)
);

CREATE OR REPLACE TABLE `Projects` (
  `id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
  'Name' VARCHAR(255) NOT NULL,
	`Creator` INTEGER NOT NULL,
	`Group` INTEGER,
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `Groups` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` VARCHAR(255) NOT NULL,
	`Master` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);

CREATE OR REPLACE TABLE `Usergroups` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`User` INTEGER NOT NULL,
	`Group` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);

ALTER TABLE `Tasks`
ADD FOREIGN KEY(`Project`) REFERENCES `Projects`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Projects`
ADD FOREIGN KEY(`Group`) REFERENCES `Groups`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Groups`
ADD FOREIGN KEY(`Master`) REFERENCES `Users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Projects`
ADD FOREIGN KEY(`Creator`) REFERENCES `Users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Usergroups`
ADD FOREIGN KEY(`User`) REFERENCES `Users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Usergroups`
ADD FOREIGN KEY(`Group`) REFERENCES `Groups`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
