CREATE OR REPLACE TABLE `Users` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Firstname` LINESTRING NOT NULL,
	`Lastname` LINESTRING NOT NULL,
	`Email` LINESTRING NOT NULL,
	`Password` LINESTRING NOT NULL,
	`Admin` BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY(`id`)
);

CREATE INDEX `Users_index_0`
ON `Users` (`id`);
CREATE OR REPLACE TABLE `Tasks` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` LINESTRING NOT NULL,
	`Creation` DATETIME NOT NULL,
	`Due` DATETIME,
	`Recurrency` SMALLINT,
	`Done` BOOLEAN NOT NULL DEFAULT FALSE,
	`Notes` MULTILINESTRING,
	`Project` INTEGER NOT NULL,
	PRIMARY KEY(`id`, `Project`)
);

CREATE OR REPLACE TABLE `Projects` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Creator` INTEGER,
	`Group` INTEGER,
	PRIMARY KEY(`id`, `Creator`)
);

CREATE OR REPLACE TABLE `Groups` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Name` LINESTRING NOT NULL,
	`Master` INTEGER NOT NULL,
	`Slaves` INTEGER,
	PRIMARY KEY(`id`)
);

ALTER TABLE `Tasks`
ADD FOREIGN KEY(`Project`) REFERENCES `Projects`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Projects`
ADD FOREIGN KEY(`Group`) REFERENCES `Groups`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Groups`
ADD FOREIGN KEY(`Master`) REFERENCES `Users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Projects`
ADD FOREIGN KEY(`Creator`) REFERENCES `Users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Groups`
ADD FOREIGN KEY(`Slaves`) REFERENCES `Users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;